### PR TITLE
Add reverse support for ExpandableListView.

### PR DESCRIPTION
**Pull request by OverSwift**
This will make headers work properly when reverse is true

### CODE REVIEW

**Comment by tp7309** [comment]
Thank you for your submission, I will merge this pull request and my local new features at this weekend.

**Comment by tp7309** [comment]
Unfortunately this is not the desired behavior, [right way](https://github.com/letsar/flutter_sticky_header/blob/master/example/lib/examples/reverse.dart).

**Comment by OverSwift** [comment]
@tp7309 oh i see this is like 2 different behaviours. For my app i need an behaviour what i have done, this is for chat when headers at top ,dates in my case, but content goes from bottom of the list. In proposed desired behaviour all goes from bottom. As i think this lib can support both for different purposes.
Would be ok to leave reverse property for list content and add new one like reverseHeaders just for headers handle it on layout?

**Comment by tp7309** [comment]
Good idea.

**Pull request merged**
